"""GPU NNUE trainer for MiniChess (6x5).

Reads self-play shards produced by tools/nnue_gen.cpp, trains a
360 -> H1 -> H2 -> 1 MLP (ReLU hidden, tanh output) on a blend of the
game result (WDL) and the teacher search score, and emits
src/policy/nnue_weights.hpp in the format src/policy/nnue.hpp expects.

Record format (little-endian):
  uint8 nfeat | int16 feat[nfeat] | uint8 stm | int8 wdl | int16 score

Usage:
  uv run python tools/train_nnue.py --h1 256 --h2 32 --epochs 80 \
      --lam 0.7 --score-scale 400 --out-scale 600
"""
import argparse
import glob
import struct
import time

import numpy as np
import torch
import torch.nn as nn

NF = 360


def parse_shard(path):
    buf = open(path, "rb").read()
    n = len(buf)
    i = 0
    rows, cols = [], []
    stms, wdls, scores = [], [], []
    sidx = 0
    while i < n:
        nf = buf[i]; i += 1
        f = np.frombuffer(buf, dtype="<i2", count=nf, offset=i); i += 2 * nf
        cols.append(f.astype(np.int32))
        rows.append(np.full(nf, sidx, dtype=np.int32))
        stms.append(buf[i]); i += 1
        v = buf[i]; i += 1
        wdls.append(v - 256 if v > 127 else v)
        scores.append(int.from_bytes(buf[i:i + 2], "little", signed=True)); i += 2
        sidx += 1
    return (sidx, np.concatenate(rows) if rows else np.empty(0, np.int32),
            np.concatenate(cols) if cols else np.empty(0, np.int32),
            np.asarray(wdls, np.float32), np.asarray(scores, np.float32))


def load_data(pattern):
    paths = sorted(glob.glob(pattern))
    if not paths:
        raise SystemExit(f"no shards match {pattern}")
    all_rows, all_cols, all_wdl, all_score = [], [], [], []
    base = 0
    t0 = time.time()
    for p in paths:
        n, rows, cols, wdl, score = parse_shard(p)
        all_rows.append(rows + base)
        all_cols.append(cols)
        all_wdl.append(wdl)
        all_score.append(score)
        base += n
        print(f"  {p}: {n} samples ({time.time()-t0:.1f}s)")
    rows = np.concatenate(all_rows)
    cols = np.concatenate(all_cols)
    wdl = np.concatenate(all_wdl)
    score = np.concatenate(all_score)
    N = base
    X = np.zeros((N, NF), np.float32)
    X[rows, cols] = 1.0
    print(f"Total {N} samples, {time.time()-t0:.1f}s to load")
    return X, wdl, score


class Net(nn.Module):
    """Single-hidden net 360 -> H -> 1 (matches src/policy/nnue.hpp).

    Kept single-layer on purpose: the inference recomputes the accumulator
    from scratch at every search leaf, so a dense second layer (H1*H2 madds)
    was measured to cost ~5 plies of search depth -- a net loss in this
    tactical game. Width + data quality buy strength far more cheaply.
    """
    def __init__(self, h):
        super().__init__()
        self.l1 = nn.Linear(NF, h)
        self.l2 = nn.Linear(h, 1)

    def forward(self, x):
        x = torch.relu(self.l1(x))
        return torch.tanh(self.l2(x)).squeeze(-1)


def fmt_array(name, arr, per_line=8):
    out = [f"inline const float {name}[{arr.size}] = {{"]
    line = []
    for i, v in enumerate(arr):
        line.append(f"{v:.8g}f,")
        if (i + 1) % per_line == 0:
            out.append("".join(line)); line = []
    if line:
        out.append("".join(line))
    out.append("};")
    return "\n".join(out)


def export(model, h, out_scale, n_samples, path):
    W1 = model.l1.weight.detach().cpu().numpy()     # [H, NF]
    B1 = model.l1.bias.detach().cpu().numpy()        # [H]
    W2 = model.l2.weight.detach().cpu().numpy()[0]   # [H]
    B2 = float(model.l2.bias.detach().cpu().numpy()[0])

    # Inference layout (matches src/policy/nnue.hpp):
    #   W1[feature*H + h]  -> W1_torch.T  (feature-major)
    #   W2[h] ; B2 scalar
    W1_flat = W1.T.reshape(-1)

    with open(path, "w") as f:
        f.write("#pragma once\n")
        f.write("// Auto-generated by tools/train_nnue.py. Do not edit.\n")
        f.write(f"// samples: {n_samples}, arch: 360 -> {h} -> 1\n")
        f.write("namespace nnue_data {\n")
        f.write(f"constexpr int   NUM_FEATURES = {NF};\n")
        f.write(f"constexpr int   HIDDEN       = {h};\n")
        f.write(f"constexpr float OUT_SCALE    = {out_scale:.1f}f;\n")
        f.write(fmt_array("W1", W1_flat) + "\n")
        f.write(fmt_array("B1", B1) + "\n")
        f.write(fmt_array("W2", W2) + "\n")
        f.write(f"inline const float B2 = {B2:.8g}f;\n")
        f.write("} // namespace nnue_data\n")
    print(f"Wrote {path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default="data/part_*.bin")
    ap.add_argument("--hidden", type=int, default=256)
    ap.add_argument("--epochs", type=int, default=80)
    ap.add_argument("--batch", type=int, default=8192)
    ap.add_argument("--lr", type=float, default=1e-3)
    ap.add_argument("--wd", type=float, default=1e-5)
    ap.add_argument("--lam", type=float, default=0.7, help="WDL weight in target")
    ap.add_argument("--score-scale", type=float, default=400.0)
    ap.add_argument("--out-scale", type=float, default=600.0)
    ap.add_argument("--out", default="src/policy/nnue_weights.hpp")
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()

    torch.manual_seed(args.seed)
    np.random.seed(args.seed)
    dev = "cuda" if torch.cuda.is_available() else "cpu"
    print("device:", dev)

    X, wdl, score = load_data(args.data)
    target = args.lam * wdl + (1 - args.lam) * np.tanh(score / args.score_scale)
    target = target.astype(np.float32)

    N = X.shape[0]
    perm = np.random.permutation(N)
    n_val = max(1, int(N * 0.04))
    val_idx, tr_idx = perm[:n_val], perm[n_val:]

    Xg = torch.from_numpy(X).to(dev)
    yg = torch.from_numpy(target).to(dev)
    tr = torch.from_numpy(tr_idx).to(dev)
    va = torch.from_numpy(val_idx).to(dev)
    Xva, yva = Xg[va], yg[va]

    model = Net(args.hidden).to(dev)
    opt = torch.optim.Adam(model.parameters(), lr=args.lr, weight_decay=args.wd)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=args.epochs)
    lossf = nn.MSELoss()

    ntr = tr.numel()
    best_val = 1e9
    best_state = None
    for ep in range(args.epochs):
        model.train()
        idx = tr[torch.randperm(ntr, device=dev)]
        tot = 0.0
        for s in range(0, ntr, args.batch):
            b = idx[s:s + args.batch]
            xb, yb = Xg[b], yg[b]
            opt.zero_grad()
            out = model(xb)
            loss = lossf(out, yb)
            loss.backward()
            opt.step()
            tot += loss.item() * b.numel()
        sched.step()
        model.eval()
        with torch.no_grad():
            vloss = lossf(model(Xva), yva).item()
        if vloss < best_val:
            best_val = vloss
            best_state = {k: v.detach().clone() for k, v in model.state_dict().items()}
        if (ep + 1) % 5 == 0 or ep == 0:
            print(f"epoch {ep+1}/{args.epochs}  train_mse={tot/ntr:.5f}  val_mse={vloss:.5f}  lr={sched.get_last_lr()[0]:.2e}")

    if best_state is not None:
        model.load_state_dict(best_state)
    print(f"best val_mse={best_val:.5f}")
    export(model, args.hidden, args.out_scale, N, args.out)


if __name__ == "__main__":
    main()
